services:
  gh-rust:
    image: gh-rust
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    working_dir: /workdir
    volumes:
      - ${PWD}:/workdir
      - /tmp/.X11-unix:/tmp/.X11-unix:ro        
      - ~/.gitconfig:/home/ubuntu/.gitconfig
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=$DISPLAY
      - LOCAL_UID=${HOST_UID}
      - LOCAL_GID=${HOST_GID}
