services:
  gh-rust:
    image: gh-rust
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    working_dir: /workdir
    volumes:
      - .:/workdir
      - ~/.gitconfig:/home/$(id -un)/.gitconfig
    tty: true
    stdin_open: true
