#!/bin/sh
set -e


# ex: ~/.local/share/gh/extensions/gh-rust/
TOP=$(dirname "$0")
# My name is gh-xxx
MYNAKE=$(basename "$0")

if [ "$1" = "build" ]; then
  docker compose -f "${TOP}/docker-compose.yml" build
  exit 0
fi

if [ "$1" = "shell" ]; then
  shift
  docker compose -f "${TOP}/docker-compose.yml" run \
    --user $(id -u):$(id -g) \
    --volume .:/workdir \
    -q --name ${MYNAKE} --rm ${MYNAKE} $@
  exit 0
fi
